import { Player, ScenarioPreset, FinancialConfig, BadgeDefinition, MatchHistoryRecord } from '../types';

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: 'deathmatch',
    name: 'Team Deathmatch / Mata-Mata',
    shortName: 'Mata-Mata',
    tagline: 'Eliminação total até o último sobrevivente',
    description: 'Combate direto entre esquadrões. Cada eliminação conta como ponto ou vitória instantânea ao limpar a equipe adversária.',
    objective: 'Elimine todos os operadores adversários antes que o tempo esgote.',
    defaultDurationMinutes: 8,
    iconName: 'Crosshair',
  },
  {
    id: 'ctf',
    name: 'Captura de Bandeira (CTF)',
    shortName: 'Captura Bandeira',
    tagline: 'Infiltre, capture e traga a bandeira para a base',
    description: 'Infiltre o perímetro inimigo, capture a bandeira central ou rival e retorne para a base segura da sua equipe.',
    objective: 'Entregue a bandeira na base do seu esquadrão sem ser alvejado no trajeto.',
    defaultDurationMinutes: 10,
    iconName: 'Flag',
  },
  {
    id: 'vip',
    name: 'Resgate de Refém / Escolta VIP',
    shortName: 'Escolta VIP',
    tagline: 'Proteja o operador VIP com colete de alto contraste',
    description: 'Um esquadrão deve escoltar o VIP (equipado com fita/colete chamativo) até o ponto de extração. O time rival deve neutralizar o VIP.',
    objective: 'Alfa escolta o VIP até a Zona Segura. Bravo tenta eliminar o VIP antes da extração.',
    defaultDurationMinutes: 7,
    iconName: 'ShieldAlert',
  },
  {
    id: 'koth',
    name: 'Rei do Pedaço (King of the Hill)',
    shortName: 'Rei do Pedaço',
    tagline: 'Conquiste e sustente o bunker central',
    description: 'Controle a zona fortificada no centro do campo. O esquadrão que mantiver a posição pelo tempo estipulado leva a rodada.',
    objective: 'Garanta superioridade numérica dentro da zona alvo demarcada.',
    defaultDurationMinutes: 10,
    iconName: 'Crown',
  },
];

export const BADGE_DEFINITIONS: Record<string, BadgeDefinition> = {
  cannon_fodder: {
    id: 'cannon_fodder',
    name: 'Bucha de Canhão',
    icon: '🪖',
    description: 'Primeiro operador eliminado na rodada.',
    humorTip: 'Foi o primeiro a testar se as tintas estavam funcionando bem na máscara!',
    colorClass: 'border-amber-500/40 bg-amber-500/10 text-amber-400',
  },
  ghost_operator: {
    id: 'ghost_operator',
    name: 'Operador Fantasma',
    icon: '🎯',
    description: 'Venceu o round sem receber nenhum tiro ou respingo.',
    humorTip: 'Invisível aos olhos e aos canos dos adversários. Nem poeira pegou no uniforme.',
    colorClass: 'border-emerald-500/40 bg-emerald-500/10 text-emerald-400',
  },
  trigger_happy: {
    id: 'trigger_happy',
    name: 'Gatilho Nervoso',
    icon: '💰',
    description: 'Gastou o maior número de bolinhas e esvaziou os loaders.',
    humorTip: 'A fábrica de tintas agradece o patrocínio! Dispara primeiro, mira depois.',
    colorClass: 'border-orange-500/40 bg-orange-500/10 text-orange-400',
  },
  vip_protector: {
    id: 'vip_protector',
    name: 'Guarda-Costas',
    icon: '🛡️',
    description: 'Elemento fundamental na extração ou defesa do VIP.',
    humorTip: 'Levou tiro na canela para o VIP cruzar a linha de chegada vivo.',
    colorClass: 'border-cyan-500/40 bg-cyan-500/10 text-cyan-400',
  },
  field_general: {
    id: 'field_general',
    name: 'General de Campo',
    icon: '🎖️',
    description: 'Acumulou 3 ou mais premiações de MVP da rodada.',
    humorTip: 'Comanda o esquadrão com autoridade e mira calibrada.',
    colorClass: 'border-purple-500/40 bg-purple-500/10 text-purple-400',
  },
  sharpshooter: {
    id: 'sharpshooter',
    name: 'Tiro Certeiro',
    icon: '⚡',
    description: 'Taxa de vitória superior a 65% na temporada.',
    humorTip: 'Raramente perde um confronto quando entra no campo de combate.',
    colorClass: 'border-blue-500/40 bg-blue-500/10 text-blue-400',
  },
};

export const INITIAL_PLAYERS: Player[] = [
  {
    id: 'p-01',
    callsign: 'Ghost',
    name: 'Lucas Silva',
    skillLevel: 5,
    role: 'Sniper',
    status: 'confirmed',
    hasOwnGear: true,
    extraAmmoPacks: 2,
    stats: { matches: 14, wins: 10, mvps: 4, eliminations: 28, deaths: 6 },
    badges: ['ghost_operator', 'field_general', 'sharpshooter'],
  },
  {
    id: 'p-02',
    callsign: 'Caveira',
    name: 'Rodrigo Antunes',
    skillLevel: 5,
    role: 'Assault',
    status: 'confirmed',
    hasOwnGear: true,
    extraAmmoPacks: 3,
    stats: { matches: 15, wins: 9, mvps: 3, eliminations: 31, deaths: 11 },
    badges: ['trigger_happy', 'field_general'],
  },
  {
    id: 'p-03',
    callsign: 'Trator',
    name: 'Marcos Vinicius',
    skillLevel: 4,
    role: 'Tank',
    status: 'confirmed',
    hasOwnGear: true,
    extraAmmoPacks: 1,
    stats: { matches: 12, wins: 8, mvps: 2, eliminations: 19, deaths: 8 },
    badges: ['vip_protector'],
  },
  {
    id: 'p-04',
    callsign: 'Fagulha',
    name: 'Gabriel Menezes',
    skillLevel: 4,
    role: 'Flanker',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 1,
    stats: { matches: 11, wins: 7, mvps: 2, eliminations: 20, deaths: 7 },
    badges: ['sharpshooter'],
  },
  {
    id: 'p-05',
    callsign: 'Viper',
    name: 'Beatriz Ramos',
    skillLevel: 4,
    role: 'Flanker',
    status: 'confirmed',
    hasOwnGear: true,
    extraAmmoPacks: 2,
    stats: { matches: 13, wins: 8, mvps: 2, eliminations: 22, deaths: 9 },
    badges: ['ghost_operator'],
  },
  {
    id: 'p-06',
    callsign: 'BalaSolta',
    name: 'Felipe Duarte',
    skillLevel: 3,
    role: 'Assault',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 4,
    stats: { matches: 10, wins: 5, mvps: 1, eliminations: 14, deaths: 12 },
    badges: ['trigger_happy'],
  },
  {
    id: 'p-07',
    callsign: 'Coruja',
    name: 'Thiago Nogueira',
    skillLevel: 3,
    role: 'Sniper',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 0,
    stats: { matches: 9, wins: 4, mvps: 1, eliminations: 12, deaths: 8 },
    badges: [],
  },
  {
    id: 'p-08',
    callsign: 'Sentinela',
    name: 'Carlos Eduardo',
    skillLevel: 3,
    role: 'Tank',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 1,
    stats: { matches: 10, wins: 5, mvps: 0, eliminations: 11, deaths: 10 },
    badges: ['vip_protector'],
  },
  {
    id: 'p-09',
    callsign: 'Zero-Um',
    name: 'Daniel Faria',
    skillLevel: 2,
    role: 'Assault',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 0,
    stats: { matches: 8, wins: 3, mvps: 0, eliminations: 7, deaths: 11 },
    badges: ['cannon_fodder'],
  },
  {
    id: 'p-10',
    callsign: 'Recruta',
    name: 'Matheus Prado',
    skillLevel: 2,
    role: 'Flanker',
    status: 'confirmed',
    hasOwnGear: false,
    extraAmmoPacks: 0,
    stats: { matches: 6, wins: 2, mvps: 0, eliminations: 5, deaths: 9 },
    badges: ['cannon_fodder'],
  },
  {
    id: 'p-11',
    callsign: 'Sombra',
    name: 'Camila Torres',
    skillLevel: 4,
    role: 'Sniper',
    status: 'bench',
    hasOwnGear: true,
    extraAmmoPacks: 1,
    stats: { matches: 7, wins: 5, mvps: 1, eliminations: 15, deaths: 5 },
    badges: ['ghost_operator'],
  },
  {
    id: 'p-12',
    callsign: 'Muralha',
    name: 'André Soares',
    skillLevel: 3,
    role: 'Tank',
    status: 'bench',
    hasOwnGear: false,
    extraAmmoPacks: 1,
    stats: { matches: 8, wins: 4, mvps: 0, eliminations: 9, deaths: 8 },
    badges: [],
  },
  {
    id: 'p-13',
    callsign: 'Predador',
    name: 'Leonardo Dias',
    skillLevel: 5,
    role: 'Assault',
    status: 'absent',
    hasOwnGear: true,
    extraAmmoPacks: 2,
    stats: { matches: 12, wins: 8, mvps: 3, eliminations: 26, deaths: 7 },
    badges: ['field_general', 'sharpshooter'],
  },
  {
    id: 'p-14',
    callsign: 'Tático',
    name: 'Renan Barreto',
    skillLevel: 3,
    role: 'Flanker',
    status: 'absent',
    hasOwnGear: false,
    extraAmmoPacks: 0,
    stats: { matches: 5, wins: 2, mvps: 0, eliminations: 6, deaths: 6 },
    badges: [],
  },
];

export const INITIAL_FINANCIAL: FinancialConfig = {
  venueCost: 400.0, // Locação do campo (R$)
  boxPrice: 180.0, // Caixa com 2000 bolinhas
  ballsPerBox: 2000,
  gearRentalPrice: 35.0, // Aluguel de marcador, máscara e colete
  communityBoxesCount: 2, // 2 caixas compradas coletivamente
  extraPackPrice: 30.0, // Preço pacote extra de bolinhas
  pixKey: '11998877665',
  pixKeyType: 'Telefone',
  organizerName: 'Lucas "Ghost" (Capitão)',
};

export const INITIAL_MATCH_HISTORY: MatchHistoryRecord[] = [
  {
    id: 'match-101',
    date: '2026-09-15T16:30:00Z',
    scenario: 'deathmatch',
    scenarioName: 'Team Deathmatch',
    durationMinutes: 8,
    teamAlpha: {
      name: 'Alfa',
      score: 5,
      playerIds: ['p-01', 'p-03', 'p-05', 'p-07', 'p-09'],
    },
    teamBravo: {
      name: 'Bravo',
      score: 3,
      playerIds: ['p-02', 'p-04', 'p-06', 'p-08', 'p-10'],
    },
    winner: 'Alfa',
    mvpPlayerId: 'p-01',
    firstEliminatedPlayerId: 'p-09',
    ghostOperativeIds: ['p-01'],
    notes: 'Alfa limpou a área com ótimo avanço pelos flancos.',
  },
  {
    id: 'match-102',
    date: '2026-09-15T17:15:00Z',
    scenario: 'vip',
    scenarioName: 'Resgate de VIP',
    durationMinutes: 6,
    teamAlpha: {
      name: 'Alfa',
      score: 2,
      playerIds: ['p-01', 'p-03', 'p-05', 'p-07', 'p-09'],
    },
    teamBravo: {
      name: 'Bravo',
      score: 4,
      playerIds: ['p-02', 'p-04', 'p-06', 'p-08', 'p-10'],
    },
    winner: 'Bravo',
    mvpPlayerId: 'p-02',
    firstEliminatedPlayerId: 'p-10',
    notes: 'Bravo interceptou o comboio VIP na área do bunker.',
  },
  {
    id: 'match-103',
    date: '2026-09-08T15:45:00Z',
    scenario: 'ctf',
    scenarioName: 'Captura de Bandeira',
    durationMinutes: 10,
    teamAlpha: {
      name: 'Alfa',
      score: 3,
      playerIds: ['p-01', 'p-04', 'p-05', 'p-08'],
    },
    teamBravo: {
      name: 'Bravo',
      score: 1,
      playerIds: ['p-02', 'p-03', 'p-06', 'p-07'],
    },
    winner: 'Alfa',
    mvpPlayerId: 'p-05',
    firstEliminatedPlayerId: 'p-06',
    notes: 'Viper infiltrou pelo galpão e garantiu a entrega da bandeira.',
  },
];
